name: Tests

on: push

jobs:
  test:
    name: Test Tesla
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: [kovan, fork]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Setup Node"
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: "Setup project"
        run: |
          yarn
      - name: "Run tests"
        run: |
          yarn test:${{ matrix.chain }}
